import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar, AppHeader } from "./features/sidebar";
import { cookies } from "next/headers";
import Toaster from "@/components/ui/sonner";

const inter = Inter({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard | authoritycars.pl",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} antialiased dark`}>
                <SidebarProvider defaultOpen={defaultOpen}>
                    <AppSidebar />
                    <main className="w-full">
                        <AppHeader />
                        {children}
                    </main>
                </SidebarProvider>
                <Toaster />
            </body>
        </html>
    );
}
