import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/features/global/navbar";

const inter = Inter({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Authoritycars | Landing Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} antialiased dark`}>
                <section className="grid grid-cols-1 md:grid-cols-7">
                    <Navbar className="sticky top-0 bottom-0 left-0 col-span-1" />
                    <main className="col-span-1 flex w-full flex-col overflow-y-auto md:col-span-6">
                        {children}
                    </main>
                </section>
            </body>
        </html>
    );
}
